background-color={{colors.primary_container.default.hex}}
text-color={{colors.on_primary_container.default.hex}}
border-color={{colors.primary.default.hex}}
border-radius=8
border-size=2
font=JetBrains Mono 11
width=350
height=100
margin=10
padding=10
default-timeout=5000
